version: '3'
services: 
  
  mongo:
    image: mongo
    container_name: 'mongo_container'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=UnitsDb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
   




  game:
    build: ./
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mongo